title: Anypoint Platform Patterns
author: Gerald Loeffler
email: gerald@integrational.eu
github_username: integrational
rss: rss
markdown: GFM
theme: minima
plugins:
  - jekyll-sitemap
  - jekyll-feed
collections:
  patterns:
    output: true
titles_from_headings:
  strip_title: true
  collections: true
minima:
  date_format: "%Y-%m-%d %H:%M"
feed:
  tags: true
defaults:
  - scope:
      type: patterns
    values:
      layout: page
header_pages:
  - patterns.md
# keywords:
# for 'about' in patterns use: "a" (= architecture), "d" (= development), "o" (= operation) 
AP: "[Anypoint Platform](https://www.mulesoft.com/platform)"
