title: Anypoint Platform Patterns
author: Gerald Loeffler
email: gerald@integrational.eu
#twitter_username: jekyllrb
github_username:  GeraldLoeffler
markdown: GFM
#remote_theme: broccolini/swiss
theme: minima
plugins:
  - jekyll-sitemap
  - jekyll-feed
feed:
  tags: true
